### ISSUE TITLE
Issue in 02_ingest/monthlyupdate/ingest_flights.py

### ISSUE THREAD

**Issue by FaizySaeed** [GoogleCloudPlatform/data-science-on-gcp#26]
In the download function,

response = urlopen(url, PARAMS)

TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.

I am getting type error because PARAMS need to be encoded in bytes. However when I try the following code, still there is error.

PARAMS = urllib.parse.urlencode(PARAMS).encode("utf-8")

**Comment by lakshmanok** [comment]
Are you using Python3? Could you try using Python 2?

https://stackoverflow.com/questions/30760728/python-3-urllib-produces-typeerror-post-data-should-be-bytes-or-an-iterable-of

**Comment by FaizySaeed** [comment]
Isn't there any way I can run this on python3. I have tried the link as well, but still not working in python3.

**Comment by lakshmanok** [comment]
Ultimately, I need to go through the codebase and migrate the code to python3.
I've been holding off because Apache Beam currently is python2 only:

https://issues.apache.org/jira/browse/BEAM-1251

So, two options:
(1) please use python 2 for now
(2) skip this chapter's code. I have the data already stored in a gcs bucket, and in the next chapter, you can simply copy my data instead of ingesting directly from the BTS

**Comment by FaizySaeed** [comment]
I got the data by running bash scripts you provide.
I guess I will revert to option 2 and for now skip this code.

Thanks for responding. I appreciate your feedback.
