### ISSUE TITLE
Uses version of BigQuery Python Client Library that is out of date

### ISSUE THREAD

**Issue by alixhami** [GoogleCloudPlatform/data-science-on-gcp#27]
This repo uses an old version of the BigQuery Python Client Library and does not specify which version.

I work on the BigQuery Python Client Library and can help with updating the code, but the versions of the required libraries should be specified (requirements.txt or otherwise).

**Comment by lakshmanok** [comment]
Because this is a book, each directory is essentially a different chapter, it is not your typical installable package.  For example,

https://github.com/GoogleCloudPlatform/data-science-on-gcp/blob/master/04_streaming/simulate/simulate.py

is meant to be run from the command-line (in CloudShell), so I'm at the mercy of whatever version of the client library is installed by default on CloudShell.

**Comment by alixhami** [comment]
I'm seeing google-cloud-bigquery version 1.3.0 when I run `pip freeze` and `pip3 freeze` on cloud shell with a new account. This is a more recent version than this repo uses and the code will not run with it. Does the book instruct users to perform any installations?

**Comment by lakshmanok** [comment]
No. So, the book came out in Jan 2018 and I've been updating the code as people file issues ... if you want to update the code and issue a PR, I'll happily take it.  Else, I will try to get to it after NEXT
